### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by MAHALAKSHMIRAMKUMAR** [sakship31/Text-steganography#1]
Why you have not used database in this project or used?
how it work explain? 
reply to:srinidhipdkt@gmail.com

**Comment by sakship31** [comment]
Answering here as well to clarify other similar questions in case someone else has the same one.
The database isn't required for this project as we aren't storing secret messages. Because of the algorithm we use, the messages are correctly decrypted and the secret is revealed on the portal if the password for decryption entered by the user is the same as the password for encrypting. If the password entered by the user who wishes to reveal secrets is incorrect, the decrypted text will also be incorrect.
